name             'promet_php-cookbook'
maintainer       'gregpalmier'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures promet_php-cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends		 'apt'
depends		 'yum'
depends		 'php'
